### ISSUE TITLE
Architecture for protocolui components

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#142]
- [x] export the gd sdk to a package
  - are env variables available in packages a react app uses? for example our REACT_APP_NETWORK, probably need solution for that
- [ ] ui package
   - [x] default nativebase theme with current G$ colors/fonts
   - [x] core components folder(buttons etc)
   - [x] advanced components folder (hold multiple core components)
   - [ ] pages folder
   - [ ] hooks folder
   - [x] contexts folder
- [ ] contexts
  - [ ] WalletsProvider - The app using our UI package should provide this context and implement the following
     - [x] multicall(chainId) - main app should return a web3 instance that could read from blockchain with chainId
     - [x] switchChain - request from the main app to switch network
     - [ ] #366
  - [ ] ProfileProvider
     - userProfile - the current user profile
     - getProfile(address) - main app should return a profile for this wallet address if exists
     - setProfile(profile) - request main app to update the current user profile

**Comment by L03TJ3** [comment]
- [ ] https://github.com/GoodDollar/GoodProtocolUI/issues/154
