### ISSUE TITLE
Add blocknative

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#163]
### **Description**
Wallet connect and web3-react has a variety of issues, why we will look into adding blocknative as a solution for connecting wallets

### **Proposed Changes**
- [x]  Install as a base start @web3-onboard/core @web3-onboard/react @web3-onboard/common @web3-onboard/injected @web3-onboard/walletconnect
- [x]  Add onboard react-hooks
#reference -- https://docs.blocknative.com/onboard/react-hooks
- [x] Update Context provider to take provider from onboard
- [x] Update Supported Wallets
  Define supported wallets in Onboard({}) initalization
  Add injected / walletconnect modules
  Return Onboard
- [x] Update eagerlyConnect to connect based on localStorage
- [x] Design

### **Todo's**
- [x] load transaction list
- [x] Update/Change inActiveListener
- [x] add unsupportedchain error
- [ ] Which others wallets to add?
- [ ] Add localization
- [x] Update UI on feedback designer
- [ ] Update outdated comments
- [ ] #229
- [x] Properly handle ropsten/kovan

### **Current Bugs**

**General**
- [x] User Rejection when using auto-select not handled properly (patch fixed)
- [ ] #169 

**wallet-connect**
- [x] Disconnecting wallet-connect doesn't work - temporary fix

**MetaMask**
- [x] Fuse/Eth cannot get the balance when using metamask on desktop (works with wallet-connect?)

**CoinBase**
- [x] #170 

**Nice to haves**
- [x] add some loaders when balances are loading 
- [x] #177 (Maybe disable at first, to add it at a later date)

**Comment by sirpy** [comment]
@L03TJ3 also need to replace usages of useWeb3React

**Comment by artqadev** [comment]
Verified

FYI:
On **Change** nothing happens:
![change.png](https://images.zenhubusercontent.com/61f900b1abe9693c0abd099b/3dbbefd1-7402-41d2-bddb-d6806759ca67)
![image.png](https://images.zenhubusercontent.com/61f900b1abe9693c0abd099b/57dbd619-2e6b-40e3-8535-4b3d436c3db0)

**Comment by L03TJ3** [comment]
Good catch, will create a new issue for it
