### ISSUE TITLE
Implement savings feature

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#210]
**Details**
We want to implement the savings feature.

**Tasks**

General
- [x] add web3provider context

Savings Page
- [ ] UI

Deposit/Withdraw/Claim Modal
- [ ] UI
- [x] Stake
- [x] Withdraw
- [x] Claim Rewards
- [x] Update modal on txReceipt Status

Savings (stakers) Info
- [x] Add a SavingsAccount component
- [x] Display active saving stats
- [ ] UI

**Additional context**
https://discourse.gooddollar.org/t/gip-5-allocating-part-of-ubi-inflation-towards-g-savings-account/114
