### ISSUE TITLE
Feature: Add support for the ZenGo wallet

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#219]
**Description**
The idea is to have ZenGo as an option on the wallet-selection screen of Onboard. Would also be nice if the in-app wallet of ZenGo functions when navigating to goodswap

**Tasks**
- [x] Create module based on wallet-connect
- [x] Test on Desktop and mobile(android)
- [ ] Add ZenGo to the preferred list on mobile (IOS) / perhaps desktop?
- [ ] Test on mobile(IOS)
- [ ] Properly support ZenGo's in-app browser when navigating to GoodSwap
