### ISSUE TITLE
User should be whitelisted with original chainid tag

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#296]
If we plan to have Invite rewards also on Celo we need to know on which chain the user was originally whitelisted, so invite reward can be claimed only on one chain.

To accomplish that we need
- [x] goodswap trigger FV flow with chainId (#302)
- [x] fv flow should send to server (along with face payload) the chainid (GoodDAPP/#3884)
  - for standalone flow the chainid is read from url params
  - for wallet get chainid from goodwallet provider
- [x] goodserver should receive chainid on fv endpoint (done #301)
  - call the new `function whitelist(address _user,string memory _did,uint256 orgChain,uint256 dateAuthenticated)` method on the adminWallet contract
  - for production env have a feature flag and still call the old `whitelist(address,string did)`
- [x] upgrade fuse dev/staging with new adminwallet+identity contract (done in v2.0 of GoodProtocol package)
