### ISSUE TITLE
Getting people to donate to the protocol 

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#50]
- [ ] cool video or infogram explaining donations
- [ ] simple interface to donate
- [ ] integrate with simplex etc...

**Comment by sepu85** [comment]
Please see https://giveth.io/project/gooddollar

@sirpy what do you have in mind with "video" and integrations?

**Comment by sirpy** [comment]
video - could be just one of the video we already have, just so people understand what it is.
or an explanation about the donation, showing that it is like an endownment that will generate UBI for ever

integrations - well basically just a fiat gateway, send user to buy dai/eth so he can then donate to the donations contract

**Comment by decentralauren** [comment]
@sirpy this ended up in sprint 11 backlog - moving into "New Issues" to explore how to do this after reserve relaunch!

**Comment by decentralauren** [comment]
@sirpy need direction on:
* Who we are targeting
* What our value prop is (what we are asking them to do and why)
* WHat tooling we want to integrate to support donations
* Where we want them to be able to donate (which channel - via site, gooddapp, etc)

**Comment by EmekaManuel** [comment]
has the requirements for this been finalized ? and it is available for a fix ?
